export const orderMappings = {
  dob: 'dob',
  type: 'type',
  size: 'size',
  name: 'name',
  base64: 'base64',
  CDScode: 'CDScode',
  phoneNo: 'phoneNo',
  address: 'address',
  lastName: 'lastName',
  firstName: 'firstName',
  signature: 'signature',
  requestedBy: 'requestedBy',
  requestDate: 'requestDate',
  districtName: 'districtName',
  yearsAttended: 'yearsAttended',
  requestedType: 'requestedType',
  releaseToName: 'releaseToName',
  releaseToEmail: 'releaseToEmail',
  industrySectors: 'industrySectors',
  classDescription: 'classDescription',
  typeOfTranscript: 'typeOfTranscript',
  districtStudentSSID: 'districtStudentSSID',
  uploadSignatureFilename: 'uploadSignatureFilename',
};

export const districtFields = [
  orderMappings.dob,
  orderMappings.CDScode,
  orderMappings.lastName,
  orderMappings.firstName,
  orderMappings.requestedBy,
  orderMappings.districtName,
  orderMappings.requestedType,
  orderMappings.requestedBy,
  orderMappings.releaseToEmail,
  orderMappings.typeOfTranscript,
  orderMappings.districtStudentSSID,
];

export const studentFields = [
  orderMappings.dob,
  orderMappings.CDScode,
  orderMappings.address,
  orderMappings.phoneNo,
  orderMappings.lastName,
  orderMappings.firstName,
  orderMappings.signature,
  orderMappings.requestedBy,
  orderMappings.districtName,
  orderMappings.requestedType,
  orderMappings.yearsAttended,
  orderMappings.releaseToName,
  orderMappings.releaseToEmail,
  orderMappings.industrySectors,
  orderMappings.classDescription,
  orderMappings.typeOfTranscript,
];
