export const DENIED = 'denied';
export const RESEND = 'resend';
export const FAILED = 'failed';
export const PENDING = 'pending';
export const APPROVED = 'approved';
export const COMPLETED = 'completed';
export const PROCESSING = 'processing';
export const READY_TO_EMAIL = 'email queued';
export const READY_TO_REVIEW = 'ready to review';
