module.exports = {
  DEFAULT_VALUE: null,
  REQUIRED: 'REQUIRED',
  REQUIRED_IF_EXISTS: 'REQUIRED_IF_EXISTS',
  OPTIONAL: 'OPTIONAL',
  TYPE_FIELD: 'TYPE_FIELD',
  TYPE_ENTITY_ARRAY: 'TYPE_ENTITY_ARRAY',
  TYPE_ENTITY: 'TYPE_ENTITY',
  CURRENT_DATE: 'CURRENT_DATE',
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  STANDARD: 'standard',
  ROP: 'rop'
};